---
- hosts: "{{ group | mandatory }}"
  sudo: true
  tasks:
    - name:  create ops group
      group: name={{ users_config.ops_group_name | mandatory }} state=present

    - name: create users
      user: name={{ item.username }} group={{ users_config.ops_group_name }}
        groups=sudo state=present shell=/bin/bash
      with_items: users_config.authorized_keys

    - name: allow sudo without password to all members of ops group
      lineinfile: "dest=/etc/sudoers state=present
        regexp='%{{ users_config.ops_group_name }} ALL'
        line='%{{ users_config.ops_group_name }} ALL=NOPASSWD: ALL'"

    - name: create key directory
      file: path=/etc/ssh/authorized_keys state=directory
        owner=0 group={{users_config.ops_group_name}} mode=0750

    - name: upload user keys
      lineinfile: "dest=/etc/ssh/authorized_keys/{{ item.username }}
        state=present
        line='{{ item.ssh_key }}'
        create=yes
        owner={{ item.username }} group=ops mode=640"
      with_items: users_config.authorized_keys

    - name: sshd configuration file update
      template: src=sshd_config.j2
        dest=/etc/ssh/sshd_config
        backup=yes
        owner=0 group=0 mode=0644
        validate='/usr/sbin/sshd -T -f %s'
      notify:
        - restart sshd

  handlers:
    - name: restart sshd
      service: name=ssh state=restarted